

== Specification Description

[[sec_4.1]]
=== S-129 General Data Product Description

General data product information.

*Title:*:: *UKCM* Information Product Specification

*Abstract:*:: UKCM Services are generally used in conjunction with ENC (<<S_101>>)
and route information for aiding ships in safe passage through shallow waters. <<S_421>>
Route Exchange Data Format, if available, is considered the preferred method for
providing route information. This S-129 UKCM Product Specification details the information
typically provided by a UKCM Service Provider.

*Content:*:: A conformant data product contains features associated with UKCM.
The specific content is defined by the Feature Catalogue and the Application Schema.

*Spatial Extent:*

*Description:*:: Global coverage of maritime areas.

*Purpose:*:: The data shall be produced for the purposes of UKCM.

[[sec_4.2]]
=== Data Product Specification Metadata

NOTE: This information uniquely identifies this Product Specification and provides
information about its creation and maintenance. For further information on dataset
metadata, see the metadata clause (Chapter 19 - Metadata).

*Title:*:: The International Hydrographic Organization Under Keel Clearance Management
Product Specification

*S-100 Version:*:: 5.2.0

*S-129 Version:*:: 2.0.0

*Date:*:: December 2024

*Language:*:: English

*Classification:*:: Unclassified

*Contact:*::
+
--
International Hydrographic Organization, +
4b quai Antoine 1er, +
B.P. 445 +
MC 98011 MONACO CEDEX +
Telephone: +377 93 10 81 00 +
Telefax: +377 93 10 81 40 +
Email: mailto:info@iho.int[info@iho.int]
--

*URL:*:: link:http:/www.iho.int[www.iho.int]

*Identifier:*:: S-129

*Maintenance:*:: Changes to the Product Specification S-129 are coordinated by the
IHO S-100 Working Group (S-100WG) and must be made available via the IHO web site.
Maintenance of the Product Specification must conform to IHO Technical Resolution
2/2007, as amended.

[[sec_4.3]]
=== IHO Product Specification Maintenance

==== Introduction

Changes to S-129 will be released by the IHO as a New Edition, a revision, or as
a document that includes clarification. These are described below.

==== New Editions

_New Editions_ introduce significant changes. _New Editions_ enable new concepts,
such as the ability to support new functions or applications, or the introduction
of new constructs or data types. _New Editions_ are likely to have a significant
impact on either existing users or future users of S-129. All cumulative _revisions_
and _clarifications_ must be included with the release of approved New Editions.

==== Revisions

_Revisions_are defined as substantive semantic changes. Typically, _revisions_ will
introduce changes to correct factual errors; introduce necessary changes that have
become evident as a result of practical experience or changing circumstances. A _revision_
must not be classified as a clarification. _Revisions_ could have an impact on either
existing users or future users of this specification. All cumulative _clarifications_
must be included with the release of approved corrections revisions.

Changes in a revision are minor and ensure backward compatibility with the previous
versions within the same Edition. Newer revisions, for example, introduce new features
and attributes. Within the same Edition, a dataset of one version could always be
processed with a later version of the feature and portrayal catalogues.

In most cases, a new feature or portrayal catalogue will result in a revision of
this specification.

==== Clarifications

_Clarifications_ are non-substantive changes. Typically, _clarifications_: remove
ambiguity; correct grammatical and spelling errors; amend or update cross references;
insert improved graphics in spelling, punctuation and grammar. A _clarification_
must not cause any substantive semantic changes.

Changes in clarifications are minor and ensure backward compatibility with the previous
versions within the same Edition. Within the same Edition, a dataset of one clarification
version could always be processed with a later version of the feature and portrayal
catalogues, and a portrayal catalogue can always rely on earlier versions of the
feature catalogues.

==== Version Numbers

The associated version control numbering to identify changes (n) to S-129 must be
as follows:

New Editions denoted as *n*.0.0

Revisions denoted as n.*n*.0

Clarifications denoted as n.n.*n*
