

[[annex-c]]
[appendix,obligation="informative"]
== Feature Catalogue

The Feature catalogue (FC) is a document that describes the content of a data model
which is an abstraction of reality that may be used to depict geographic datasets.
The FC for S-129 describes the details of Application Schema in <<sec_7.2>> of this
Product Specification with GML and it is verified by the FCB (Feature Catalogue Builder)
published by KHOA on behalf of IHO.

=== Catalogue header information

Name: Under Keel Clearance Management

Scope: Dynamic under keel clearance management information

Field of Application: Under keel clearance management

Version Number: 2.0.0

Version date: 2024-09-28

Producer information:

Individual name:

Organisation name: International Hydrographic Organization

Position Name:

Contact Information:

Phone:

Address:

[cols="6",options="header,unnumbered"]
|===
| deliveryPoint | city | administrativeArea | postalCode | country | electronicMailAddress

| International Hydrographic Organization, +
4 quai Antoine 1er, +
B.P. 445
| | | MC 98011 MONACO CEDEX | |

|===

Online resource information:

Hours of Service:

Contact Instructions:

Role: user

Classification: unclassified

<<<

=== Definition Sources

No definition sources in catalogue.

<<<

=== Simple Attributes

==== Generation Time

*Name*: Generation Time

*Definition*: Time the UKC plan was generated.

*Code*: `'generationTime'`

*Remarks*:

*Aliases*: (none)

*Value Type*: dateTime

==== Vessel ID

*Name*: Vessel ID

*Definition*:

*Code*: `'vesselID'`

*Remarks*: Vessel identifier, based on MRN. Can be either IMO or MMSI based.

*Aliases*: (none)

*Value Type*: text

==== Source Route Name

*Name*: Source Route Name

*Definition*: Identification of the route used as a source for the calculation.

*Code*: `'sourceRouteName'`

*Remarks*: May be provided through different methods, such as <<S_421>>, RTZ, or
as generated by the UKCM service. If provided, for example, using <<S_421>>, the
value of "S-421.Route.routeID" is used for machine-readable identification, or the
value of "S-421.RouteInfo.routeInfoName" is used for human-readable identification.

*Aliases*: (none)

*Value Type*: text

==== Source Route Version

*Name*: Source Route Version

*Definition*: Identification of the route used as a source for the calculation.

*Code*: `'sourceRouteVersion'`

*Remarks*: May be provided through different methods, such as <<S_421>>, RTZ, or
as generated by the UKCM service. Can be used to supplement information provided
by "sourceRouteName", especially if "sourceRouteName" provides insufficient route
information. If provided, for example, using <<S_421>>, the value of
"S-421.Route.routeEditionNo" is used.

*Aliases*: (none)

*Value Type*: integer

==== Maximum Draught

*Name*: Maximum Draught

*Definition*: The maximum vessel draught in metres, used as base for the calculation.

*Code*: `'maximumDraught'`

*Remarks*:

*Aliases*:

*Value Type*: real

*Unit of measure:*

*name*: metre

*symbol*: m

*Constraints*:

[cols="5",options="header,unnumbered"]
|===
| String Length | Text Pattern 2+| Range | Precision

.3+| (not specified) .3+| (none) | lowerBound | 0 .3+| (not specified)
| upperBound | (not specified)
| closure | gtSemiInterval

|===

==== Distance Above UKC Limit

*Name*: Distance Above UKC Limit

*Definition*: The distance of the lowest part of the ship's keel above the established
Under Keel Clearance Limit for the waterway, expressed in metres.

*Code*: `'distanceAboveUKCLimit'`

*Remarks*:

*Aliases*:

*Value Type*: real

*Unit of measure:*::
*name:*::: metre
*symbol:*::: m

==== Scale Minimum

*Name*: Scale Minimum

*Definition*: The minimum scale at which the feature may be used for example for
ECDIS presentation.

*Code*: `'scaleMinimum'`

*Remarks*: The modulus of the scale is indicated, that is 1:1 250 000 is encoded
as 1250000.

*Aliases*:

*Value Type*: integer

==== Language

*Name*: Language

*Definition*: The method of human communication, either spoken or written, consisting
of the use of words in a structured and conventional way.

*Code*: `'language'`

*Remarks*:

*Aliases*:

*Value Type*: text

==== Name

*Name*: Name

*Definition*: The individual name of a feature.

*Code*: `'name'`

*Remarks*:

*Aliases*:

*Value Type*: text

==== Expected Passing Time

*Name*: Expected Passing Time

*Definition*: The expected passing time for a ship for a nominated Under Keel Clearance
Control Point.

*Code*: `'expectedPassingTime'`

*Remarks*:

*Aliases*:

*Value Type*: dateTime

==== Expected Passing Speed

*Name*: Expected Passing Speed

*Definition*: The expected passing speed for a ship for a nominated Under Keel Clearance
Control Point.

*Code*: `'expectedPassingSpeed'`

*Remarks*:

*Aliases*:

*Value Type*: real

*Unit of measure:*::
*name:*::: metres per second
*symbol:*::: m/s

*Constraints*:

[cols="5",options="header,unnumbered"]
|===
| String Length | Text Pattern 2+| Range | Precision

.3+| (not specified) .3+| (none) | lowerBound | 0 .3+| (not specified)
| upperBound | (not specified)
| closure | geSemiInterval

|===

==== Interoperability Identifier

*Name*: Interoperability Identifier

*Definition*: A common unique identifier for entities which describe a single real-world
feature, and which is used to identify instances of the feature in end-user systems
where the feature may be included in multiple data product types.

*Code*: `'interoperabilityIdentifier'`

*Remarks*:

*Aliases*:

*Value Type*: URN

==== Time Start

*Name*: Time Start

*Definition*: The start time of an active period.

*Code*: `'timeStart'`

*Remarks*:

*Aliases*:

*Value Type*: dateTime

==== Time End

*Name*: Time End

*Definition*: The end time of an active period.

*Code*: `'timeEnd'`

*Remarks*:

*Aliases*:

*Value Type*: dateTime

<<<

=== Enumerations

==== Name Usage

Name: Name Usage

Definition: Classification of the type and display level of the name of a feature
in an end-user system.

Code: `'nameUsage'`

Remarks:

Aliases: (none)

Value Type: enumeration

.Listed Values
[cols="4",options="header,unnumbered"]
|===
| Label | Definition | Code | Remarks

| `'defaultNameDisplay'` +
Aliases: (none)
| The name is intended to be displayed when the end-user system is set to the default
name/text display setting.
| 1 |

| `'alternateNameDisplay'` +
Aliases: (none)
| The name is intended to be displayed when the end-user system is set to an alternate
name/text display setting, for example an alternate language.
| 2 |

|===

==== Under Keel Clearance Purpose

Name: Under Keel Clearance Purpose

Definition: The relevant phase of a UKC passage plan.

Code: `'underKeelClearancePurpose'`

Remarks:

Aliases: (none)

Value Type: enumeration

.Listed Values
[cols="4",options="header,unnumbered"]
|===
| Label | Definition | Code | Remarks

| `'Pre Plan'` +
Aliases: (none)
| An indicative UKC plan that identifies potential sailing windows for a nominated
vessel draught; days, weeks or months prior to the planned passage through the UKCM
region.
| 1 |

| `'Actual Plan'` +
Aliases: (none)
| A detailed Under Keel Clearance plan that identifies sailing windows and no-go
areas, integrating live weather data, hours or days prior to transiting the Under
Keel Clearance Management region.
| 2 |

| `'Actual Update'` +
Aliases: (none)
| A near real-time, detailed, Under Keel Clearance plan that identifies sailing windows
and no-go areas, using live weather, vessel position and traffic data, while the
vessel is transiting the Under Keel Clearance Management region.
| 3 |

|===

==== Under Keel Clearance Calculation Requested

Name: Under Keel Clearance Calculation Requested

Definition: Indication of the aim of the UKC plan: To find the maximum safe vessel
draught for transiting the UKCM region, or to find sailing windows for a nominated
vessel draught.

Code: `'underKeelClearanceCalculationRequested'`

Remarks:

Aliases: (none)

Value Type: Enumeration

.Listed Values
[cols="4",options="header,unnumbered"]
|===
| Label | Definition | Code | Remarks

| `'Time Window'` +
Aliases: (none)
| The available time window(s) for a given draught.
| 1 |

| `'Maximum Draught'` +
Aliases: (none)
| The maximum draught for a given time window.
| 2 |

|===

=== Complex Attributes

==== Fixed Time Range

Name: Fixed Time Range

Definition: Time interval.

Code: `'fixedTimeRange'`

Remarks:

Aliases: (none)

.Sub-Attributes
[cols="5",options="header,unnumbered"]
|===
| Sub-attribute | Type | Mult. | Permitted Values | sequential

| timeStart | dateTime | [0..1] | | false
| timeEnd   | dateTime | [0..1] | | false
|===

==== Feature Name

Name: Feature Name

Definition: Provides the name of an entity, defines the national language of the
name, and provides the option to display the name at various system display settings.

Code: `'featureName'`

Remarks:

Aliases: (none)

.Sub-Attributes
[cols="5",options="header,unnumbered"]
|===
| Sub-attribute | Type | Mult. | Permitted Values | sequential

| language | text | [1] | | false
| name     | text | [1] | | false

| nameUsage | enumeration | [0..1]
| 1: defaultNameDisplay +
2: alternateNameDisplay | false

|===

=== Roles

==== Associations

Association(name): UKC Plan Area Composition

Definition: A feature association for the binding between Under Keel Clearance Plan
Area and Under Keel Clearance Plan

Role Type: Composition

Code: UnderKeelClearancePlanAreaComposition

Multiplicity: 0..++*++ / 1

Role: `'theComponent / theCollection'`

Feature type: UnderKeelClearancePlanArea / UnderKeelClearancePlan

Remarks: It must be in all feature types that they have connection. The featuretype
attribute is target feature.

Association(name): UKC Non Navigable Area Composition

Definition: A feature association for the binding between Under Keel Clearance Non
Navigable Area and Under Keel Clearance Plan

Role type: Composition

Code: UnderKeelClearanceNonNavigableAreaComposition

Multiplicity: 0..++*++ / 1

Role: `'theComponent / theCollection'`

Feature type: UnderKeelClearancePlanNonNavigableArea / UnderKeelClearancePlan

Remarks: It must be in all feature types that they have connection. The featuretype
attribute is target feature.

Association(name): UKC Almost Non Navigable Area Composition

Definition: A feature association for the binding between Under Keel Clearance Almost
Non Navigable Area and Under Keel Clearance Plan

Role type: Composition

Code: UnderKeelClearanceAlmostNonNavigableAreaComposition

Multiplicity: 0..++*++ / 1

Role: `'theComponent / theCollection'`

Feature type: UnderKeelClearanceAlmostNonNavigableArea / UnderKeelClearancePlan

Remarks: It must be in all feature types that they have connection. The featuretype
attribute is target feature.

Association(name): UKC Control Point Composition

Definition: A feature association for the binding between Under Keel Clearance Control
Point and Under Keel Clearance Plan

Role type: Composition

Code: UnderKeelClearanceControlPointComposition

Multiplicity: 1..++*++ / 1

Role: `'theComponent / theCollection'`

Feature type: UnderKeelClearanceControlPoint / UnderKeelClearancePlan

Remarks: It must be in all feature types that they have connection. The featuretype
attribute is target feature.

==== The Collection

Name: of the Collection

Definition: A pointer to the aggregate in a whole-part relationship.

Code: `'theCollection'`

Aliases: (none)

==== The Component

Name: The Component

Definition: A pointer to a part in a whole-part relationship

Code: `'theComponent'`

Aliases: (none)

<<<

=== Feature Types

==== UnderKeelClearancePlan

Name: Under Keel Clearance Plan

Abstract type: false

Definition: A UKC plan calculated for a particular vessel, for a particular passage

Code: `'UnderKeelClearancePlan'`

Remarks:

Aliases: (none)

Supertype: FeatureType

Feature use type: geographic

Permitted primitives: noGeometry

.Attribute Bindings
[cols="5",options="header,unnumbered"]
|===
| Attribute | Type | Mult. | Permitted Values | Sequential

| generationTime     | Simple | [0..1] | | false
| vesselID           | Simple | [0..1] | | false
| sourceRouteName    | Simple | [0..1] | | false
| sourceRouteVersion | Simple | [0..1] | | false
| maximumDraught     | Simple | [0..1] | | false

| underKeelClearancePurpose | Enumeration | [0..1]
| 1: Pre Plan +
2: Actual Plan +
3: Actual Update | false

| UnderKeelClearanceCalculationRequested | Enumeration | [0..1]
| 1: Time Window +
2: Maximum Draught | false

| interoperabilityIdentifier | URN | [0..1] | | false
| fixedTimeRange | Complex | [0..1] | | false

|===

==== UnderKeelClearancePlanArea

Name: Under Keel Clearance Plan Area

Abstract type: false

Definition: The area for which an under keel clearance plan has been calculated for
a particular vessel, for a particular passage.

Code: `'UnderKeelClearancePlanArea'`

Remarks:

Aliases: (none)

Supertype: FeatureType

Feature use type: geographic

Permitted primitives: surface

.Attribute Bindings
[cols="5",options="header,unnumbered"]
|===
| Attribute | Type | Mult. | Permitted Values | Sequential

| scaleMinimum               | Simple | 0..1 | | false
| interoperabilityIdentifier | URN    | 0..1 | | false
|===

==== UnderKeelClearanceNonNavigableArea

Name: Under Keel Clearance Non Navigable Area

Abstract type: false

Definition: An area of under keel clearance less than the calculated safe limit.

Code: `'UnderKeelClearanceNonNavigableArea'`

Remarks:

Aliases: (none)

Supertype: FeatureType

Feature use type: geographic

Permitted primitives: surface

.Attribute Bindings
[cols="5",options="header,unnumbered"]
|===
| Attribute | Type | Mult. | Permitted Values | Sequential

| scaleMinimum               | Simple | 0..1 | | false
| interoperabilityIdentifier | URN    | 0..1 | | false
|===

==== UnderKeelClearanceAlmostNonNavigableArea

Name: Under Keel Clearance Almost Non Navigable Area

Abstract type: false

Definition: An area of under keel clearance almost less than the calculated safe
limit, as established for the waterway.

Code: `'UnderKeelClearanceAlmostNonNavigableArea'`

Remarks:

Aliases: (none)

Supertype: FeatureType

Feature use type: geographic

Permitted primitives: surface

.Attribute Bindings
[cols="5",options="header,unnumbered"]
|===
| Attribute | Type | Mult. | Permitted Values | Sequential

| scaleMinimum               | Simple | 0..1 | | false
| distanceAboveUKCLimit      | Simple | 0..1 | | false
| interoperabilityIdentifier | URN    | 0..1 | | false
|===

==== UnderKeelClearanceControlPoint

Name: Under Keel Clearance Control Point

Abstract type: false

Definition: Selected critical passage point or line.

Code: `'UnderKeelClearanceControlPoint'`

Remarks:

Aliases: (none)

Supertype: FeatureType

Feature use type: geographic

Permitted primitives: point

.Attribute Bindings
[cols="5",options="header,unnumbered"]
|===
| Attribute | Type | Mult. | Permitted Values | Sequential

| featureName                | Complex | 0..1 | | false
| distanceAboveUKCLimit      | Simple  | 0..1 | | false
| expectedPassingTime        | Simple  | 0..1 | | false
| expectedPassingSpeed       | Simple  | 0..1 | | false
| interoperabilityIdentifier | URN     | 0..1 | | false
| fixedTimeRange             | Complex | 0..1 | | false
|===
